# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='admin_role',
            field=models.BooleanField(default=False),
        ),
    ]
